### ISSUE TITLE
Vendors: Show only Completed or Refunded Items

### ISSUE THREAD

**Issue by happivize** [happivize/live#18]
Right now when you are a vendor and login, it shows all sales, even if they are marked Canceled. This means all my test purchases show up.  I only want it to show items that are completed or refunded.

And in further testing, I dont' see refunded items listed either. 

I would like those to show and maybe a status column that says Completed or Refunded.

**Comment by shpp-shablyuk** [comment]
Via what vendor can I log in and see these canceled sales?

**Comment by shpp-shablyuk** [comment]
Now in the vendor plugin there are 2 groups of sales statuses: Completed (this includes 'completed' and 'processing') и Reversed (this includes 'pending', 'refunded','cancelled', 'failed'). Now the vendor dashboard shows only Completed group sales, so there are no Refunded sales. We can move Refunded orders to the Completed group. Or should I make it so that they just show up together with the Completed group?

**Comment by shpp-shablyuk** [comment]
I've added 'status' column.
https://prnt.sc/iljk5l

**Comment by happivize** [comment]
i like the status column

can that status column reflect completed or refunded

and if the order is not completed or refunded, it does not appear in the
vendors lists?

**Comment by shpp-shablyuk** [comment]
Done. Check, please.

**Comment by happivize** [comment]
I have reviewed and changed an order and it does change status from completed to refunded. But it's still showing in the top part. I've made a video:

https://www.screencast.com/t/VacecMZBD

How long do you think it would take to fix that?

**Comment by shpp-shablyuk** [comment]
fixed

**Comment by happivize** [comment]
thanks, looks good. Can you tell me how to add to live?

**Comment by shpp-shablyuk** [comment]
I sent an email with instructions.

**Comment by happivize** [comment]
i did not get that email, and i checked spam

**Comment by shpp-shablyuk** [comment]
forwarded  email to eftcolumbus@gmail.com

**Comment by happivize** [comment]
yep that is correct, it's not coming through. can you add here and I'll see if I can use what is listed here

**Comment by shpp-shablyuk** [comment]
1. You should add this snippet https://prnt.sc/inrip8
2. You should add 'reports.php' file and replace 'orders.php'  in this folder 'themes/flatsome-child/wc-vendors/dashboard/'
3. You should update this file 'orders.php' in this folder 'themes/flatsome-child/wc-vendors/orders/'
[files-for-dashboard-folder.zip](https://github.com/happivize/live/files/1789581/files-for-dashboard-folder.zip)
[file-for-orders-folder.zip](https://github.com/happivize/live/files/1789582/file-for-orders-folder.zip)

**Comment by happivize** [comment]
This didn't work. I confirmed multiple times I added the right folder into dashboard and orders. I deleted and re-did them. The snippet is activated and same # of lines as on dev.

Now I'm seeing no sales at all in the Vendor Dashboard

**Comment by shpp-shablyuk** [comment]
Could you check if the files were replaced? I see that these files have an old date
https://prnt.sc/iq8cku

**Comment by happivize** [comment]
yes i double checked that multiple times. in the folder that you sent that i downloaded, the files have a mod date of March, but when I copy them over to the site, it changes to December. I did it multiple times and it happened every single time.

**Comment by happivize** [comment]
i also tried dragging and dropping and regular uploading, it still did the same thing

**Comment by shpp-shablyuk** [comment]
Ok, could you send me your folder 'wc-vendors', I'll check the files

**Comment by happivize** [comment]
also it's weird but the new reports.php file did NOT change it's mod date as you see. 


[wc-vendors.zip](https://github.com/happivize/live/files/1804007/wc-vendors.zip)

**Comment by shpp-shablyuk** [comment]
Replace existing 'wc-vendors' folder with this folder:
[wc-vendors.zip](https://github.com/happivize/live/files/1804085/wc-vendors.zip)

**Comment by happivize** [comment]
nope, now i can't even revert back to what it is, no sales are showing at all. this isn't working

**Comment by happivize** [comment]
well i at least got it to revert back now. so the old way of showing sales are on there, with the full address and everything, none of the changes you made to it

**Comment by happivize** [comment]
i'm going to have my web admin do it

**Comment by happivize** [comment]
The web admin is part of my hosting company. I had him copy the current dev wc-vendors folder to live. It did not  help, still wouldn't show any sales. 

I have changed that one to wc-vendorsNEW and have the old wc-vendors file working again.  I deactivated the snippet. I am back now where we were before this issue of showing completed/refunded was started. I remembered that reports.php was new for this issue, so I changed that to reportsNEW.php and I have the folders back the way they were a week or so ago, and it's showing the old way.

**Comment by happivize** [comment]
this is what it looks like now:

![image](https://user-images.githubusercontent.com/28787692/37309078-2f17dc16-2616-11e8-92e9-874cde688f7c.png)


https://www.screencast.com/t/bdP5hcwfl

**Comment by shpp-shablyuk** [comment]
The structure of folders and files and their names on live site should be identical to the dev site. Or copy the live current version to the dev, I'll make the necessary changes and you'll copy them

**Comment by happivize** [comment]
I've done that at least 8 times. It's not working. I dragged and dropped
from dev to live. I downloaded and uploaded from dev to live. I had my
webadmin do it who moves folders and files all day (head guy at hosting
company). I sent you the folder from live you sent me a new zip and I did
that to upload.

Are you absolutely 100% sure that besides 1) those two orders.php file
updates 2) the new reports.php file and 3) the snippet that there is
nothing else needed?

**Comment by happivize** [comment]
here is dev next to live. you can see the one called wc-vendorsNEW is the same exact as dev. But if I change the old wc-vendors to wc-vendorsOLD and make wc-vendorsNEW just plain wc-vendors, no sales show up at all (with snippet activated).

https://www.screencast.com/t/bKqrlWIX

**Comment by shpp-shablyuk** [comment]
I'm sorry, maybe there's a mistake in the snippet. Could you update the snippet and use the wc-vendor folder from the dev site?

**Comment by happivize** [comment]
yes, when i updated the snippet and resintated the files I had copied over,
it works. phew.

**Comment by happivize** [comment]
I didn't think to check this til now, but when the vendor downloads the customers, the column doesn't show up on the xls. Please add to the report that is generated too.

**Comment by shpp-shablyuk** [comment]
Done. Check, please on dev.

**Comment by happivize** [comment]
it looks like you are omitting the refunded from the Show Orders table and the export, that's good too.

How do I add to live...(I'm dreading this)...

**Comment by shpp-shablyuk** [comment]
Update the snippet. https://prnt.sc/ir22k7

**Comment by happivize** [comment]
thanks,looks good.
